### ISSUE TITLE
Constraint test fails for some versions of sqlite

### ISSUE THREAD

**Issue by DirtNap** [BUADCP2013/CS473-EX_CMS#3]
The naive regexp matching in `_AssertConstraintError` doesn't account for differences in the error messages in various versions of sqlite.  For example, some versions report a not null error as:

    NOT NULL blah blah blah <column name>

while other versions report it as

    <column name> blah blah blah not be null

As JWZ allegedly said, 

> Some people, when confronted with a problem, think "I know, I'll use regular expressions."
> Now they have two problems.

**Comment by xorinox** [comment]
I think I get the issue but I would be curious how to approach resolving it.

**Comment by DirtNap** [comment]
First, I'm going to create a branch to work on this issue.  Here's how I do that (basically following [these instructions](https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches)):

First I need to be in the `master` branch.  I almost always want to branch from `master` for an issue that exists in `master`.  I run

    git checkout master

When I do, I see this result:

![git branch result](https://cloud.githubusercontent.com/assets/410264/6393394/b1d75342-bd97-11e4-9f7e-4a8ccbfe58f1.png)

I want my branch to be up to date, so first I get master up to date by doing:

    git pull

I've now got the master branch up to date after the merge of #1.  Now I want to create a branch to work this issue.  All I have to do is `checkout` with the -b argument, to create the branch I'm targeting:

    git checkout -b Issue3

Now I could do some work, but I would like to first push the branch to github and get it set up for collaboration, so I do:

    git push origin Issue3

`origin` is just a keyword that's set up in your repo for "where you got this from".  Since I cloned this repo from github.com, it's already set to be this repo, so that command sends the Issue3 branch up to this repo.  The next thing I need to do is tell git I want to sync back and forth, so I do:

    git branch --set-upstream-to=origin/Issue3 Issue3

Now the upstream branch for my local `Issue3` is `origin/Issue3`, which is to say `github.com/BUADCP2013/CS473-EX_CMS/Issue3`.  Now I can `pull` or `push` my branch.  Of course, I don't need to, because nothing has changed:

![git pull](https://cloud.githubusercontent.com/assets/410264/6393543/f713a5b8-bd98-11e4-9768-cf283d6e1b67.png)

**Comment by DirtNap** [comment]
#### The scope of the problem

The next thing I have to do is find the scope of the problem.  In my new branch, I'll run the unit tests by doing:

    python -m unittest discover -v

...and I get this result:

![beacon successful tests](https://cloud.githubusercontent.com/assets/410264/6393564/3a51cf1c-bd99-11e4-9d5b-6729d6cfea76.png)

This looks good.  **beacon** is a macbook pro running OSX Yosemite, and whatever version of sqlite comes with that system.  Let's try it somewhere else.  **letterbucket.net** is an amazon ec2 linux with some other version of sqlite installed.  Let's see what happens.

![ec2 failed tests](https://cloud.githubusercontent.com/assets/410264/6393645/dcabd532-bd99-11e4-8aa7-e819dbcd9f5a.png)

To see what's going on here, I'm going to look at the function producing the error:

```python
    def _AssertConstraintError(self, callable, type, column, msg='', *args, **kwargs):
        re = ''.join((r'.*\b', type.upper(), r'\b.*\b', column.lower(), r'\b.*'))
        if msg:
            try:
                with self.assertRaisesRegexp(IntegrityError, re):
                    callable(*args, **kwargs)
            except AssertionError as ex:
                raise AssertionError('%s (%s)' % (msg, ex.message))
        else:
            self.assertRaisesRegexp(IntegrityError, re, callable, *args, **kwargs)
        db.session.rollback()
```

This function takes a callable (a function or method passed as an argument) and calls it inside the `assertRaisesRegexp` method provided by the `unittest.TestCase` class, which is the parent class of our test.  This suppresses any `IntegrityError`s it catches, and tries to match the message in the exception with the regexp we create as `re`.  For debugging, it would be worth seeing the actual message, so I add the line:

        callable(*args, **kwargs)

above the `if msg:` line.  This is going to call the failing method without the suppression, and we'll see the output:

![Raw Failure](https://cloud.githubusercontent.com/assets/410264/6393787/082203ac-bd9b-11e4-8e25-a336d1a0eea9.png)

The error message is `(IntegrityError) UNIQUE constraint failed: user.username ` followed by the SQL statement which produced the error.  That matches our regexp, so that's why our test passes.  Why is it failing on other systems?  I can safely commit to the Issue3 branch and push it to github, which I do as 38683e0d1ad7af21f037897170790ffa06d3b03d.  

Now I can pull this down on ec2 and see what the difference is.

![ec2 raw failure](https://cloud.githubusercontent.com/assets/410264/6393905/e2074690-bd9b-11e4-8de9-931db7d7dda1.png)

The error message here is `(IntegrityError) column username is not unique`.  Aha!  That's the problem -- that's different than our expected message from the mac.  Now we know what we need to fix.

**Comment by DirtNap** [comment]
#### Fixing the problem

The problem we have comes down to this -- to validate that there was a UNIQUE constraint on the user column, we were usint the following regular expression:

    .*\bUNIQUE\b.*\buser\b.*

This says that we expect to see a bunch of anything (`.*`) followed by the word UNIQUE (`\bUNIQUE\b`) (the `\b` says that this is the boundary of a word -- it doesn't match anything itself, it just makes sure we don't match the word UNIQUELY, for example) followed by more of anything (`.*`) and then the word user (`\buser\b`) followed to the end by anything else (`.*`).  There are two issues with our approach in the face of these variant error messages.  First, the case is indeterminate.  That's easily solved, regular expressions syntax includes the ability to ignore case.  However, the larger problem is that we do not know the order of the constraint vs the column name.  In this case, instead of looking for a pattern which matches the entire string, we can look for a pattern at the beginning of the string using a technique called a look-ahead.  This regular expression:

    ^(?=\bUNIQUE\b)(?=\buser\b)(?i)

says "Match the beginning of a line (`^`) where there exists somewhere after it (`(?=)`) the word UNIQUE (`\bUNIQUE\b`) _and also_ exists somewhere after it (`(?=)`) the word user (`\buser\b`), regardless of case (`(?i)`)".  This should suit us well.  I'll make the change (on another macbook with a "bad" version of sqlite) and remove our debugging call, and everything should be great:

![sqlite not null variant](https://cloud.githubusercontent.com/assets/410264/6398155/92624362-bdb7-11e4-9631-bf4c2f9cfc19.png)

Oh No!  Now we have an even bigger problem.  In our first version of sqlite, a NOT NULL constraint error had the words NOT NULL.  ...in this version, it uses the phrase "may not be NULL".  That's just terrible.  Well, what we clearly need is a regular expression like `\bNOT\b.*?\bNULL\b`.  Now we know how to fix all of our problems.  ...but we have a design issue here.  It was easy for people using the test code to know what kind of constraint they were testing, and to pass its name in to `_AssertConstraintError`, but asking everyone to remember all these regular expressions doesn't work so well.  We need a better designed solution.

**Comment by DirtNap** [comment]
#### Implementing the solution

To get the fix into working shape and make it maintainable, I'm going to choose to separate the testing infrastructure here from our `UserModelTest`.  I create a `utilities` package and a `testing` module within it by doing this:

```bash
    mkdir -p letterbucket/utilities
    touch letterbucket/utilities/__init__.py
```

and then I add this to the file `letterbucket/utilities/testing.py`:

```python
import unittest
from sqlalchemy.exc import IntegrityError

class DbModelTestCase(unittest.TestCase):
    """A Utility class for easier testing of SQLAlchemy Models."""

    # Constant regular expression fragments                                                                                                                                                                                                   
    NOT_NULL_ASSERTION_RE = r'\bNOT\b.*?\bNULL\b'
    UNIQUE_ASSERTION_RE = r'\bUNIQUE\b'

    def _AssertConstraintError(self, db, type_re, column, callable, msg='', *args, **kwargs):
        re = ''.join((r'^(?=.*', type_re, r')(?=.*\b', column.lower(), r'\b)(?i)'))
        if msg:
            try:
                with self.assertRaisesRegexp(IntegrityError, re):
                    callable(*args, **kwargs)
            except AssertionError as ex:
                raise AssertionError('%s (%s)' % (msg, ex.message))
        else:
            self.assertRaisesRegexp(IntegrityError, re, callable, *args, **kwargs)
        db.session.rollback()
```

Now I've captured the necessary regular expressions in one place, and updated the method syntax to be a little more modular.  When I go back to `test_users.py`, I need to change the parent class from:

```python
class UserModelTest(unittest.TestCase):
```
to:
```python
class UserModelTest(testing.DbModelTestCase):
```

Then, for each stanza like:

```python
            second_user.email = new_user.email
            self._AssertConstraintError(second_user.Persist, 'UNIQUE', 'email',
                                        msg='Email must be unique.')
            second_user.email = self.fake_data.email()
```
I modify it like this:
```python
            second_user.email = new_user.email
            self._AssertConstraintError(db, self.UNIQUE_ASSERTION_RE, 'email',
                                        second_user.Persist,
                                        msg='Email must be unique.')
            second_user.email = self.fake_data.email()
```

![Success](https://cloud.githubusercontent.com/assets/410264/6399029/e7037b88-bdbd-11e4-9f29-cb8881d4fee1.png)

Success!  Now I add my new and changed files to my local checkout:

    git add letterbucket/utilities/__init__.py
    git add letterbucket/utilities/testing.py
    git add letterbucket/account/test_users.py

and commit (which is 84c6dc09b80f7cae86a68017ad8f5ce19014dae7.)

Finally, I create a pull request for my Issue3 branch back in to master (#4).
